#### 1. Import the numpy package under the name `np`

In [12]:
import numpy as np

#### 2. Create a null vector  of size 20

In [10]:
z=np.zeros(20)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a Ones Vector of size 20

In [32]:
o=np.ones(20)
print(o)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### 4.  Create a boolean array of 3X4.

In [33]:
arr = [True, False]

bool_arr = np.random.choice(arr, size=(3,4))

print(bool_arr)

[[False  True False  True]
 [ True  True  True False]
 [ True False False False]]


#### 5.  Create a vector with values ranging from 100 to 200 of float64 data type

In [56]:
x = np.arange(100,200, dtype=np.float64)
print(x)


array([100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 151., 152., 153., 154.,
       155., 156., 157., 158., 159., 160., 161., 162., 163., 164., 165.,
       166., 167., 168., 169., 170., 171., 172., 173., 174., 175., 176.,
       177., 178., 179., 180., 181., 182., 183., 184., 185., 186., 187.,
       188., 189., 190., 191., 192., 193., 194., 195., 196., 197., 198.,
       199.])

##### 6.Create an array of five values evenly spaced between 0 and 1

In [61]:
np.linspace( 0 , 1 , 5 )


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### 7.  Reverse a given Vector

In [62]:
myarray = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
a=np.flip(myarray)



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 8. Find indices of non-zero elements from \[12,34,0,4,0,2,3,0,123\]

In [80]:
y=np.array([12,34,0,4,0,2,3,0,123])
np.where(y!=0)

(array([0, 1, 3, 5, 6, 8], dtype=int32),)

#### 9. Replace all even numbers in given arr vector with -1

In [95]:

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
s=np.where(arr%2==0,-1,arr)
print(s)

[ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1]


#### 10. Replace all odd numbers in arr with -1 without changing arr

In [96]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
z = np.where(arr % 2==1 , -1,arr)
print(s)

[ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1]


#### 11. Create a 5x3 array with random values ( In - between 100 to 300) and find the minimum and maximum values  ( Hints : Use np.random.random)

In [106]:
r = np.random.randint(100,300,size=(5,3))
print(r)
print("min : ",np.min(r))
print("max : ",np.max(r))




[[229 282 218]
 [299 254 266]
 [158 295 149]
 [148 214 291]
 [111 230 140]]
min :  111
max :  299


#### 12. Create a random vector of size 30 and find the mean value

In [120]:
v=np.random.random(30)
print(v)
print("mean: ",np.mean(v)) 

[0.54696799 0.74076335 0.19501846 0.10303025 0.7750182  0.81907503
 0.80184706 0.63131362 0.93212607 0.68381122 0.06719487 0.53367069
 0.69660207 0.27811174 0.03826488 0.58608722 0.02527604 0.92596839
 0.22516264 0.9562814  0.25868596 0.78094262 0.61398803 0.95015493
 0.78043028 0.58871584 0.59765044 0.66832273 0.94924595 0.15781509]
mean:  0.5635847691196839


#### 17. What is the result of the following expression? 

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
false

#### 18. Normalize a 5x5 random matrix (Hints -  fourmula  (x - mean) / std)

In [130]:

Z = np.random.random((5,5))

Z=(Z-np.mean(Z))/np.std(Z)
print(Z)



[[ 0.27942187 -0.2486544   0.2774626  -0.32493706 -0.35255127]
 [-1.87910175  1.43677208  0.60584922 -1.25410064 -0.84924816]
 [-0.53990305 -2.08090019  1.55966162  0.73347418  0.4005811 ]
 [ 1.25793102 -1.19529452  0.21404042 -0.25859182  0.66281567]
 [ 1.12924088  0.2904643   1.44430867 -1.23708205 -0.07165871]]


#### 19. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [138]:
x = np.random.rand(5,3)
y = np.random.rand(3,2)
x.dot(y)

array([[0.32797181, 1.2215528 ],
       [0.51439496, 1.37079999],
       [0.27936929, 1.18390282],
       [0.54701501, 1.22161292],
       [0.62552317, 1.50617057]])

#### 20. How to find common values between two arrays?

In [144]:
x = np.random.randint(1,20,size=15)
y = np.random.randint(1,50,size=15)
np.intersect1d(x,y)

array([ 3, 13])

#### 21. How to get the dates of yesterday, today and tomorrow?

In [151]:
print("yesterday",np.datetime64('today', 'D') - np.timedelta64(1, 'D'))
print("today",np.datetime64('today', 'D') )
print("tomorrow",np.datetime64('today', 'D') + np.timedelta64(1, 'D'))

yesterday 2021-06-25
today 2021-06-26
tomorrow 2021-06-27


#### 22. How to get all the dates corresponding to the month of July 2016?

In [156]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 23. Extract Integer part from vector

In [176]:
Z = np.array([1.234,2.345,5.678,666.543,123.99])


Z.astype(int)

array([  1,   2,   5, 666, 123])

#### 24. Convert a 1D array to a 2D array with 4 rows

In [188]:
one = np.arange(2,22)

one=one.reshape(4,5)
one


array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21]])

#### 25. Create two array ( a and b ) and stack them vertically?.( concatenate vertically?)

In [193]:
a = np.random.randint(1,20,size=5)
b = np.random.randint(1,20,size=5)
np.vstack([a,b])


array([[10, 15, 19, 15,  1],
       [14,  9,  2, 19,  3]])

#### 26. Create two 2Darray ( a and b ) and stack them horizontally.( concatenate horizontally)

In [199]:
x = np.random.rand(2,2)
y = np.random.rand(2,2)
np.hstack([x,y])

array([[1, 1, 1, 3, 3, 3],
       [2, 2, 2, 4, 4, 4]])

#### 27. Create two 2Darray ( a and b ) and stack last tow colums of b into a horizontally.( concatenate horizontally)

In [209]:
x = np.arange(1,11).reshape([2,5])
y = np.arange(11,21).reshape([2,5])

print(x)
print(y)

np.hstack([x[:,-2:],y[:,-2:]])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 4,  5, 14, 15],
       [ 9, 10, 19, 20]])

#### 28. Create a 2darray of 4X4 and swap 2nd  and 4th column .

In [227]:
x = np.arange(1,17).reshape([4,4])

x[:,[1,3]]=x[:,[3,1]]
print(x)



[[ 1  4  3  2]
 [ 5  8  7  6]
 [ 9 12 11 10]
 [13 16 15 14]]


#### 29. Create a 2darray of 4X4 and swap 2nd and 4th rows 

In [229]:
x = np.arange(16).reshape([4,4])
x[[1,3],:]=x[[3,1],:]
x

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])

In [1]:
pip install pandoc


  Running setup.py install for pandoc: started
    Running setup.py install for pandoc: finished with status 'done'
Note: you may need to restart the kernel to use updated packages.


You are using pip version 19.0.3, however version 21.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
